import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TeamIdService {

  // Index is equal to the line number minus 9
  teamArray =
     ['Air Force',
      'Akron',
      'Alabama',
      'Appalachian State',
      'Arizona',
      'Arizona State',
      'Arkansas',
      'Arkansas State',
      'Army',
      'Auburn',
      'Ball State',
      'Baylor',
      'Boise State',
      'Boston College',
      'Bowling Green',
      'BYU',
      'Buffalo',
      'California',
      'Central Michigan',
      'Charlotte',
      'Cincinnati',
      'Clemson',
      'Colorado',
      'Colorado State',
      'Connecticut',
      'Duke Blue',
      'East Carolina',
      'Eastern Michigan',
      'Florida',
      'Florida Atlantic',
      'Florida International',
      'Florida State',
      'Fresno State',
      'Georgia',
      'Georgia Tech',
      'Hawaii',
      'Houston',
      'Illinois',
      'Indiana',
      'Iowa',
      'Iowa State',
      'Kansas',
      'Kansas State',
      'Kent State',
      'Kentucky',
      'Louisiana-Lafayette',
      'Louisiana-Monroe',
      'LSU',
      'Louisiana Tech',
      'Louisville',
      'Marshall',
      'Maryland',
      'Massachusetts',
      'Memphis',
      'Miami',
      'Miami (OH)',
      'Michigan',
      'Michigan State',
      'Middle Tennessee State',
      'Minnesota',
      'Mississippi',
      'Mississippi State',
      'Missouri',
      'Navy',
      'Nebraska',
      'Nevada',
      'New Mexico',
      'New Mexico State',
      'North Carolina',
      'North Carolina State',
      'North Texas',
      'Northern Illinois',
      'Northwestern',
      'Notre Dame',
      'Ohio',
      'Ohio State',
      'Oklahoma',
      'Oklahoma State',
      'Old Dominion',
      'Oregon',
      'Oregon State',
      'Penn State',
      'Pittsburgh',
      'Purdue',
      'Rice',
      'Rutgers',
      'San Diego State',
      'San Jose State',
      'South Alabama',
      'South Carolina',
      'South Florida',
      'SMU',
      'Southern Miss',
      'Stanford',
      'Syracuse',
      'Temple',
      'Tennessee',
      'Texas',
      'Texas A&M',
      'TCU',
      'Texas State',
      'Texas Tech',
      'Toledo',
      'Troy',
      'Tulane',
      'Tulsa',
      'UAB',
      'UCF',
      'UCLA',
      'UNLV',
      'USC',
      'Utah',
      'Utah State',
      'UTEP',
      'UTSA',
      'Vanderbilt',
      'Virginia',
      'Virginia Tech',
      'Wake Forest',
      'Washington',
      'Washington State',
      'West Virginia',
      'Western Kentucky',
      'Western Michigan',
      'Wisconsin',
      'Wyoming'];

  constructor() { }

  getTeamAtIndex(index: number): string {
    return this.teamArray[index];
  }

  getIndexForTeam(teamName: string): number {
    return this.teamArray.indexOf(teamName);
  }
}
